name: docs
channels:
  - defaults
dependencies:
  - Sphinx==5.3.0
  - sphinx-autobuild==2021.3.14
  - sphinx-autodoc-typehints==1.19.5
  - sphinx-copybutton==0.5.0
  - sphinx-toolbox==3.1.2
  - Pallets-Sphinx-Themes==2.0.3
